[package]
name = "project-name"
version = "0.1.5"
authors = ["authors"]
edition = "2021"
license = "Proprietary"

[[bin]]
name = "project-name"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0"

[dependencies.niti-hal]
path = "./hdk/niti-hal"
features = ["niti-v1"]

[build-dependencies.proc-macro2]
version = "=1.0.79"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"