[package]
name = "project-name"
version = "0.1.5"
authors = ["authors"]
edition = "2021"
license = "Proprietary"

[[bin]]
name = "project-name"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0"

[dependencies.niti-hal]
path = "C:/niti/hdk/niti-hal"
{% case board -%}
  {%- when "Niti V1 Board" -%}
    features = ["niti-v1"]
  {%- when "Arduino Mega 2560" -%}
    features = ["arduino-mega2560"]
  {%- when "Arduino Nano" -%}
    features = ["arduino-nano"]
  {%- when "Arduino Nano New Bootloader" -%}
    features = ["arduino-nano"]
  {%- when "Arduino Uno" -%}
    features = ["arduino-uno"]
  {%- when "Nano168" -%}
    features = ["nano168"]
{%- endcase %}

[build-dependencies.proc-macro2]
version = "=1.0.79"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"